var GAME_LEVELS = [
  ["                                               yyyyyyyyyy                                                        ",
   "          yyyyyyyyyyyyyyyyy                    yyyyyyyyyy                         yyyyyyyyyy                     ",
   "          yyyyyyyyyyyyyyyyy                                                       yyyyyyyyyy                     ",
   "          yyyyyyyyyyyyyyyyy                                                                                      ",
   "                                                                   o                                             ",
   "                                 yyyyyy               o  o                                                       ",
   "                                 yyyyyy                           xxx                                     yyyyy  ",
   "        xxxxx                                      xxx    xxx    xx!xx                                    yyyyy  ",
   "      xxx!!!xxx                     o o      xx                  x!!!x                                           ",
   "      xx!!!!!xx                                                  xx!xx         o                                 ",
   "      xxx!!!xxx                    xxxxx                          xvx                                            ",
   "        xxxxx                                                                xxxxx                               ",
   "  x                                       o o                                x!!!x              o    o           ",
   "  x                     o                                                   xx!!!x                               ",
   "  x                                      xxxxx                             xxx!!!x             xxx  xxx          ",
   "  x          xxxx       o       o                                        xxxxx!!!x             xxx  xxx          ",
   "  x  @       x  x                                                xx xx  xxxxxx!!!x                               ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxx   xxxxxxxx!!!xxxxxxxxx!!!xxxxxxxxxxxxx!!!!!!!!!!xxxxxxxxx",
   "                              x   x                  x     x     x!!!x       x!!!x           x!!!!!!!!!!x        ",
   "                              x!!!x                  x!!!!!x     xxxxx       xxxxx           xx!!!!!!!!xx        ",
   "                              x!!!x                  x!!!!!x                                  xx!!!!!!xx         ",
   "                              xxxxx                  xxxxxxx                                   xx!!!!xx          ",
   "                                                                                                xx!!xx           ",
   "                                                                                                 xxxx            "],
  ["                                      x!!x                                                                        ",
   "                                      x!!x                                                                        ",
   "                                      x!!xxxxxxxxxx                                                               ",
   "                                      xx!!!!!!!!!!xx                                                              ",
   "                                       xxxxxxxxxx!!x                                                              ",
   "                                                xx!x                                                              ",
   "                                                 x!x                                                              ",
   "                                                 xvx                                                              ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                               x     x                                                            ",
   "                                               x     x                                                            ",
   "                                               x     x                                                            ",
   "                                               x     x                                                            ",
   "                                               xx    x                                                            ",
   "                                               x     x      o  o                                                  ",
   "                                xxxxx          x     x               xxx  o                                       ",
   "                                   xxx         x     x     xxxxxx    xxx xx                                       ",
   "            xxxxx  xxxxx     xx     xx         x    xx               xxx xx                                       ",
   "     @     xxx         x     xxx  o xx         x     x               xxx xx   o                                   ",
   "    xxxxx xxxx         x     xxxx   xx         x     x               xxx     xx                                   ",
   "    x x      x         x    xxxxx o xx         x     x               xxx     xx                                   ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!             xx   o                               ",
   "!!!!x x!!!!!!x         x!!!!!xx   o   xxxxxxxxxx     x!!!!!!!xx!                 xx                               ",
   "!!!!x x!!!!!!x         x!!!!!x                      xx!!!!!!xx !                 xx                               ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                 xx     o    o      o             ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                 xx                               ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                       xxxx xxxx   xxx            ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                       xxxx xxxx   xxx            "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                              o   o                                           ",
   "                                                     o                                                        ",
   "                                            o              xxxxxxxxxxx                                        ",
   "                                                   xxxxx   xxxxxxxxxxx                                        ",
   "                                          xxxxx    xxxxx   xxxxxxxxxxx                 o         o            ",
   "                                          xxxxx    xxxxx   xxxxxxxxxxx                                        ",
   "xxxxxxxx                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxx",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "       o       ^                                                                                       o      ",
   "   @                                                                                                           ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                            xxxxx                                                                             ",
   "                                                                                                              "],

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
